name: ecommerce_mobile_app
description: "Proyek Flutter baru."

# Mencegah publikasi tidak sengaja ke pub.dev
publish_to: "none" 

# Konfigurasi versi aplikasi
# Mengikuti aturan semantic versioning: mayor.minor.patch
version: 1.0.0+1

# Spesifikasi versi SDK Dart
environment:
  sdk: ^3.5.3 

dependencies:
  # Kerangka kerja Flutter inti
  # Menyediakan fondasi dasar untuk membangun aplikasi mobile
  flutter:
    sdk: flutter

  # Provider - Manajemen State
  # Membantu mengelola dan menyebarkan state aplikasi antar widget
  # Memudahkan pembagian data dan logika di seluruh aplikasi
  provider: ^6.0.0

  # Google Fonts - Manajemen Tipografi
  # Memungkinkan penggunaan font Google secara langsung di aplikasi
  # Memberikan variasi dan kustomisasi tipografi yang luas
  google_fonts: ^6.2.1

  # Intl - Internasionalisasi
  # Mendukung pemformatan tanggal, angka, dan fitur lokalitas lainnya
  # Penting untuk aplikasi dengan dukungan multi-bahasa
  intl: ^0.17.0

  # Font Awesome - Ikon Komprehensif
  # Menyediakan kumpulan ikon yang beragam untuk desain UI
  # Cocok untuk menambahkan ikon kustom dan menarik
  font_awesome_flutter: ^9.0.0

  # FlutterToast - Notifikasi Singkat
  # Menampilkan pesan singkat (toast) untuk memberikan umpan balik pengguna
  # Berguna untuk konfirmasi aksi atau peringatan
  fluttertoast: ^8.2.1

  # Lucide Icons - Ikon Modern
  # Menyediakan set ikon minimalis dan bersih
  # Mendukung desain UI kontemporer
  lucide_icons: 0.257.0

  # Lottie - Animasi Lanjutan
  # Mengintegrasikan animasi dari Adobe After Effects
  # Memungkinkan animasi kompleks dan menarik
  lottie: ^2.7.0

  # Timeline Tile - Widget Garis Waktu
  # Membuat tampilan garis waktu atau proses bertahap
  # Berguna untuk menunjukkan alur atau progress
  timeline_tile: ^2.0.0

  # Animate Do - Animasi Masuk/Keluar
  # Menyediakan efek animasi siap pakai untuk widget
  # Menambah interaksi visual pada transisi elemen
  animate_do: ^3.0.2

  # Image Picker - Pemilih Gambar
  # Memungkinkan pemilihan gambar dari galeri atau kamera
  # Mendukung platform iOS dan Android
  image_picker: ^1.1.2

  # Flutter Animate - Animasi Lanjutan
  # Menawarkan opsi animasi yang lebih kompleks dan dapat disesuaikan
  # Memberikan kontrol detail pada animasi
  flutter_animate: ^4.5.2

  # Cupertino Icons - Ikon iOS
  # Ikon default dari sistem desain Cupertino
  cupertino_icons: ^1.0.8

  # Firebase Core - Konfigurasi Firebase
  # Menyediakan inisialisasi dasar untuk layanan Firebase
  firebase_core: ^3.8.0

  # Firebase Authentication
  # Mendukung berbagai metode autentikasi
  # Termasuk login email/password dan Google Sign-In
  firebase_auth: ^5.3.3

  # Google Sign-In
  # Memungkinkan autentikasi menggunakan akun Google
  # Menyederhanakan proses login
  google_sign_in: ^6.1.4

  # Cloud Firestore - Database Awan
  # Database NoSQL untuk menyimpan dan mensinkronkan data aplikasi
  # Fleksibel dan real-time
  cloud_firestore: ^5.5.0

  # Firebase Cloud Messaging
  # Mendukung pengiriman dan penerimaan push notification
  # Meningkatkan interaksi pengguna
  firebase_messaging: ^15.1.5

  # Firebase Storage
  # Penyimpanan cloud untuk konten yang dibuat pengguna
  # Mendukung unggah gambar, video, dan file lainnya
  firebase_storage: ^12.3.6

  # Flutter Secure Storage
  # Menyimpan data sensitif dengan enkripsi
  # Aman untuk menyimpan token, kunci, dll
  flutter_secure_storage: ^9.2.2

  # Local Authentication
  # Mendukung autentikasi biometrik
  # Memungkinkan login dengan sidik jari atau pengenalan wajah
  local_auth: ^2.3.0

  # Shared Preferences
  # Penyimpanan lokal sederhana untuk data kunci-nilai
  # Cocok untuk menyimpan pengaturan pengguna
  shared_preferences: ^2.3.3

  # Firebase Dynamic Links
  # Membuat tautan yang bekerja di lintas platform
  # Mempertahankan konteks saat membuka aplikasi
  firebase_dynamic_links: ^6.0.11

  # Share Plus
  # Membagikan konten ke aplikasi lain
  # Mendukung berbagi teks, file, dan konten lainnya
  share_plus: ^7.2.2

  # URL Launcher
  # Membuka tautan web di browser default
  # Memudahkan navigasi eksternal
  url_launcher: ^6.3.1

dev_dependencies:
  # Alat pengujian Flutter
  flutter_test:
    sdk: flutter

  # Aturan lint resmi Flutter
  # Meningkatkan kualitas kode
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  # Direktori aset untuk berbagai kategori gambar
  assets:
    - images/
    - images/all/
    - images/shoes/
    - images/beauty/
    - images/women fashion/
    - images/men fashion/
    - images/jewelry/
    - images/icon/
    - images/eletronik/
    - assets/animations/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
